---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:2.16.*
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/weaveworks/flux-get-started
    ref: master
    path: charts/ghost
  values:
    image: bitnami/ghost:2.16.4-ol-7-r6
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    serviceType: ClusterIP
    mariadb:
      persistence:
        enabled: false
